version: "3.8"

services:
  api-gateway:
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
      target: ${NODE_ENV}
    volumes:
      - ./api-gateway:/nestjs-kafka/api-gateway/src/app
      - nestjs-kafka/api-gateway/src/app/node_modules
    command: npm run start:debug
    
  consumer:
    build:
      dockerfile: Dockerfile
      context: ./consumer
      target: ${NODE_ENV}
    volumes:
      - ./consumer:/nestjs-kafka/consumer/src/app
      - /nestjs-kafka/consumer/src/app/node_modules
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    ports:
      - 3000:3000
      - 9229:9229
    restart: always


  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: ${NODE_ENV}
    command: npm run start
    volumes:
      - ./frontend:/nestjs-kafka/frontend/src/app
      - /nestjs-kafka/frontend/src/app/node_modules
    ports:
      - 4200:4200
    links:
     - api-gateway
  
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432